""" Constants for annotations in the mapping.

The constants defined here are used to annotate the mapping tuples in cuda_to_hip_mappings.py.
They are based on
https://github.com/ROCm-Developer-Tools/HIP/blob/master/hipify-clang/src/Statistics.h
and fall in three categories: 1) type of mapping, 2) API of mapping, 3) unsupported
mapping.
"""

CONV_VERSION = 0,
CONV_INIT = 1
CONV_DEVICE = 2
CONV_MEM = 3
CONV_KERN = 4
CONV_COORD_FUNC = 5
CONV_MATH_FUNC = 6
CONV_DEVICE_FUNC = 7
CONV_SPECIAL_FUNC = 8
CONV_STREAM = 9
CONV_EVENT = 10
CONV_OCCUPANCY = 11
CONV_CONTEXT = 12
CONV_PEER = 13
CONV_MODULE = 14
CONV_CACHE = 15
CONV_EXEC = 16
CONV_ERROR = 17
CONV_DEF = 18
CONV_TEX = 19
CONV_GL = 20
CONV_GRAPHICS = 21
CONV_SURFACE = 22
CONV_JIT = 23
CONV_D3D9 = 24
CONV_D3D10 = 25
CONV_D3D11 = 26
CONV_VDPAU = 27
CONV_EGL = 28
CONV_THREAD = 29
CONV_OTHER = 30
CONV_INCLUDE = 31
CONV_INCLUDE_CUDA_MAIN_H = 32
CONV_TYPE = 33
CONV_LITERAL = 34
CONV_NUMERIC_LITERAL = 35
CONV_LAST = 36

API_DRIVER = 37
API_RUNTIME = 38
API_BLAS = 39
API_SPARSE = 40
API_RAND = 41
API_LAST = 42
API_FFT = 43
API_RTC = 44

HIP_UNSUPPORTED = 43
API_PYTORCH = 1337
API_CAFFE2 = 1338
API_C10 = 1339

# Constants for public API
VERSION = CONV_VERSION
INIT = CONV_INIT
DEVICE = CONV_DEVICE
MEMORY = CONV_MEM
KERNEL = CONV_KERN
COORDINATE_FUNCTION = CONV_COORD_FUNC
MATH_FUNCTION = CONV_MATH_FUNC
DEVICE_FUNCTION = CONV_DEVICE_FUNC
SPECIAL_FUNCTION = CONV_SPECIAL_FUNC
STREAM = CONV_STREAM
EVENT = CONV_EVENT
OCCUPANCY = CONV_OCCUPANCY
CONTEXT = CONV_CONTEXT
PEER = CONV_PEER
MODULE = CONV_MODULE
CACHE = CONV_CACHE
EXECUTION = CONV_EXEC
ERROR = CONV_ERROR
DEFINITION = CONV_DEF
TEXTURE = CONV_TEX
OPENGL = CONV_GL
GRAPHICS = CONV_GRAPHICS
SURFACE = CONV_SURFACE
JIT = CONV_JIT
DIRECT3D9 = CONV_D3D9
DIRECT3D10 = CONV_D3D10
DIRECT3D11 = CONV_D3D11
VDPAU = CONV_VDPAU
EGL = CONV_EGL
THREAD = CONV_THREAD
OTHER = CONV_OTHER
INCLUDE = CONV_INCLUDE
INCLUDE_CUDA_MAIN_H = CONV_INCLUDE_CUDA_MAIN_H
TYPE = CONV_TYPE
LITERAL = CONV_LITERAL
NUMERIC_LITERAL = CONV_NUMERIC_LITERAL
LAST = CONV_LAST
DRIVER_API = API_DRIVER
RUNTIME_API = API_RUNTIME
BLAS_API = API_BLAS
SPARSE_API = API_SPARSE
RAND_API = API_RAND
LAST_API = API_LAST
FFT_API = API_FFT
RTC_API = API_RTC
UNSUPPORTED = HIP_UNSUPPORTED
PYTORCH_API = API_PYTORCH
CAFFE2_API = API_CAFFE2
C10_API = API_C10

# All constants for public API
__all__ = [
    'VERSION',
    'INIT',
    'DEVICE',
    'MEMORY',
    'KERNEL',
    'COORDINATE_FUNCTION',
    'MATH_FUNCTION',
    'DEVICE_FUNCTION',
    'SPECIAL_FUNCTION',
    'STREAM',
    'EVENT',
    'OCCUPANCY',
    'CONTEXT',
    'PEER',
    'MODULE',
    'CACHE',
    'EXECUTION',
    'ERROR',
    'DEFINITION',
    'TEXTURE',
    'OPENGL',
    'GRAPHICS',
    'SURFACE',
    'JIT',
    'DIRECT3D9',
    'DIRECT3D10',
    'DIRECT3D11',
    'VDPAU',
    'EGL',
    'THREAD',
    'OTHER',
    'INCLUDE',
    'INCLUDE_CUDA_MAIN_H',
    'TYPE',
    'LITERAL',
    'NUMERIC_LITERAL',
    'LAST',
    'DRIVER_API',
    'RUNTIME_API',
    'BLAS_API',
    'SPARSE_API',
    'RAND_API',
    'LAST_API',
    'FFT_API',
    'RTC_API',
    'UNSUPPORTED',
    'PYTORCH_API',
    'CAFFE2_API',
    'C10_API'
]